# Copyright 2018 Etsy Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# see: https://airflow.apache.org/code.html#airflow.operators.bash_operator.BashOperator
name: bash
operator_class: BashOperator
operator_class_module: airflow.operators.bash_operator
schema_extends: base
parameters_jsonschema:
    properties:
        bash_command:
            type: string
        xcom_push:
            type: boolean
        env:
            type: object
            additionalProperties:
                type:
                    string
        output_encoding:
            type: string
    required:
        - bash_command
    additionalProperties: false
