# Copyright 2018 Etsy Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# for the native operator, see: https://github.com/apache/airflow/blob/1.10.3/airflow/contrib/operators/bigquery_to_gcs.py
# for the export_format, see: https://github.com/apache/airflow/blob/1.10.3/airflow/contrib/hooks/bigquery_hook.py#L1096-L1098\

name: bigquery_to_gcs
operator_class: BigQueryToCloudStorageOperator
operator_class_module: airflow.contrib.operators.bigquery_to_gcs 
schema_extends: base
parameters_jsonschema:
    properties:
        source_project_dataset_table:
            type: string
        destination_cloud_storage_uris:
            type: array
        compression:
            type: string
        export_format:
            type: string
            enum: [
                CSV,
                NEWLINE_DELIMITED_JSON,
                AVRO,
                GOOGLE_SHEETS,
                DATASTORE_BACKUP,
                PARQUET
            ]
        field_delimiter:
            type: string
        print_header:
            type: boolean
        bigquery_conn_id:
            type: string
        delegate_to:
            type: string
        labels:
            type: object
            additionalProperties:
                type: string

    required:
        - source_project_dataset_table
        - destination_cloud_storage_uris
