# Copyright 2018 Etsy Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

name: dataflow_template
operator_class: DataflowTemplateOperator
operator_class_module: airflow.contrib.operators.dataflow_operator
schema_extends: base
parameters_jsonschema:
    properties:
        template:
            type: string
        job_name:
            type: string
        dataflow_default_options:
            type: object
            properties:
                project:
                    type: string
                region:
                    type: string
                zone:
                    type: string
                maxWorkers:
                    type: string
                serviceAccountEmail:
                    type: string
                tempLocation:
                    type: string
                bypassTempDirValidation:
                    type: boolean
                machineType:
                    type: string
            additionalProperties: false
        parameters:
            type: object
            additionalProperties:
                type: string
        gcp_conn_id:
            type: string
        delegate_to:
            type: string
        poll_sleep:
            type: string
    required:
        - template
    additionalProperties: false
