# Copyright 2018 Etsy Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# see: https://airflow.apache.org/code.html#airflow.operators.docker_operator.DockerOperator
name: docker
operator_class: DockerOperator
operator_class_module: airflow.operators.docker_operator
schema_extends: base
parameters_jsonschema:
    properties:
        image:
          type: string
        api_version:
          type: string
        auto_remove:
          type: boolean
        command:
          type: string
        docker_url:
          type: string
        force_pull:
          type: boolean
        mem_limit:
          type: string
        host_tmp_dir:
          type: string
        network_mode:
          type: string
        tls_ca_cert:
          type: string
        tls_client_cert:
          type: string
        tls_client_key:
          type: string
        tls_hostname:
          type: string
        tls_ssl_version:
          type: string
        tmp_dir:
          type: string
        user:
          type: string
        volumes:
          type: array
          items:
            type: string
        working_dir:
          type: string
        xcom_push:
          type: boolean
        xcom_all:
          type: boolean
        docker_conn_id:
          type: string
        shm_size:
          type: integer
    required:
        - image
