# Copyright 2018 Etsy Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# see: https://github.com/apache/airflow/blob/1.10.3/airflow/operators/email_operator.py

name: email
operator_class: EmailOperator
operator_class_module: airflow.operators.email_operator
schema_extends: base
parameters_jsonschema:
    properties:
        to:
            type: array
            items:
                type: string
                format: email
        subject:
            type: string
        html_content:
            type: string
        files:
            type: array
            items:
                type: string
        cc:
            type: array
            items:
                type: string
                format: email
        bcc:
            type: array
            items:
                type: string
                format: email
        mime_subtype: 
            type: string
        mime_charset:
            type: string
    required:
        - to
        - subject
        - html_content

